package io.mosip.packet.core.constant;

import io.mosip.packet.core.constant.database.DBTypes;
import org.springframework.stereotype.Component;

import java.util.HashMap;

@Component
public class TableQueries {;
    private static HashMap<String, HashMap<DBTypes, String>> queryMap;

    public TableQueries() {
        HashMap<DBTypes, String> inserQuerytMap = new HashMap<>();
        inserQuerytMap.put(DBTypes.MYSQL, "INSERT INTO <TABLE_NAME> (RUN_INSTANCE_ID, OFFSET_VALUE, IN_USE, HASH_VALUE, FILTER_PARM) VALUES ('<RUN_INSTANCE_ID>', '<VALUE>', '<IN_USE>', '<HASH_VALUE>', '<FILTER_PARM>') ON DUPLICATE KEY UPDATE OFFSET_VALUE = '<VALUE>', IN_USE = '<IN_USE>', FILTER_PARM = '<FILTER_PARM>'");
        inserQuerytMap.put(DBTypes.POSTGRESQL, "INSERT INTO <TABLE_NAME> ( RUN_INSTANCE_ID, OFFSET_VALUE, IN_USE, HASH_VALUE, FILTER_PARM ) VALUES ('<RUN_INSTANCE_ID>', '<VALUE>', '<IN_USE>', '<HASH_VALUE>', '<FILTER_PARM>') ON CONFLICT(RUN_INSTANCE_ID, HASH_VALUE) DO UPDATE SET OFFSET_VALUE = '<VALUE>', IN_USE = '<IN_USE>', FILTER_PARM='<FILTER_PARM>'");
        inserQuerytMap.put(DBTypes.ORACLE, "MERGE INTO <TABLE_NAME> T USING (SELECT 1 FROM DUAL) C ON (T.RUN_INSTANCE_ID = '<RUN_INSTANCE_ID>' AND T.HASH_VALUE = '<HASH_VALUE>') WHEN NOT MATCHED THEN INSERT (RUN_INSTANCE_ID, OFFSET_VALUE, IN_USE, HASH_VALUE, FILTER_PARM) values('<RUN_INSTANCE_ID>', <VALUE>, '<IN_USE>', '<HASH_VALUE>', '<FILTER_PARM>') WHEN MATCHED THEN UPDATE SET OFFSET_VALUE = '<VALUE>', IN_USE = '<IN_USE>', FILTER_PARM='<FILTER_PARM>'");
        inserQuerytMap.put(DBTypes.MSSQL, "IF EXISTS (SELECT 1 FROM <TABLE_NAME> WHERE RUN_INSTANCE_ID = '<RUN_INSTANCE_ID>' AND HASH_VALUE = '<HASH_VALUE>') UPDATE <TABLE_NAME> SET OFFSET_VALUE = '<VALUE>', IN_USE = '<IN_USE>', FILTER_PARM='<FILTER_PARM>' WHERE RUN_INSTANCE_ID = '<RUN_INSTANCE_ID>' AND HASH_VALUE = '<HASH_VALUE>' ELSE INSERT INTO <TABLE_NAME> (RUN_INSTANCE_ID, OFFSET_VALUE, IN_USE, HASH_VALUE, FILTER_PARM) VALUES('<RUN_INSTANCE_ID>', <VALUE>, '<IN_USE>', '<HASH_VALUE>', '<FILTER_PARM>')");

        HashMap<DBTypes, String> inserPacketTrackerQueryMap = new HashMap<>();
        inserPacketTrackerQueryMap.put(DBTypes.MYSQL, "INSERT INTO <TABLE_NAME> (REF_ID, REG_NO, STATUS, CR_BY, CR_DTIMES, RUN_INSTANCE_ID, SESSION_ID, ACTIVITY, PROCESS, COMMENTS <IN_ADD_COL>) VALUES ('<REF_ID>', '<REG_NO>', '<STATUS>', '<CR_BY>', '<CR_DTIMES>', '<RUN_INSTANCE_ID>', '<SESSION_ID>', '<ACTIVITY>', '<PROCESS>', '<COMMENTS>' <IN_ADD_VAL>) ON DUPLICATE KEY UPDATE REF_ID = '<REF_ID>', REG_NO = '<REG_NO>', STATUS = '<STATUS>', UPD_BY = '<UPD_BY>', UPD_DTIMES = '<UPD_DTIMES>', RUN_INSTANCE_ID = '<RUN_INSTANCE_ID>', SESSION_ID = '<SESSION_ID>', ACTIVITY = '<ACTIVITY>', PROCESS = '<PROCESS>', COMMENTS = '<COMMENTS>' <IN_ADD_COL_VAL>");
        inserPacketTrackerQueryMap.put(DBTypes.POSTGRESQL, "INSERT INTO <TABLE_NAME> (REF_ID, REG_NO, STATUS, CR_BY, CR_DTIMES, RUN_INSTANCE_ID, SESSION_ID, ACTIVITY, PROCESS, COMMENTS  <IN_ADD_COL>) VALUES ('<REF_ID>', '<REG_NO>', '<STATUS>', '<CR_BY>', '<CR_DTIMES>', '<RUN_INSTANCE_ID>', '<SESSION_ID>', '<ACTIVITY>', '<PROCESS>', '<COMMENTS>'  <IN_ADD_VAL>) ON CONFLICT(RUN_INSTANCE_ID,REF_ID) DO UPDATE SET REF_ID = '<REF_ID>', REG_NO = '<REG_NO>', STATUS = '<STATUS>', UPD_BY = '<UPD_BY>', UPD_DTIMES = '<UPD_DTIMES>', RUN_INSTANCE_ID = '<RUN_INSTANCE_ID>', SESSION_ID = '<SESSION_ID>', ACTIVITY = '<ACTIVITY>', PROCESS = '<PROCESS>', COMMENTS = '<COMMENTS>' <IN_ADD_COL_VAL>");
        inserPacketTrackerQueryMap.put(DBTypes.ORACLE, "MERGE INTO <TABLE_NAME> T USING (SELECT 1 FROM DUAL) C ON (T.RUN_INSTANCE_ID = '<RUN_INSTANCE_ID>' AND T.REF_ID = '<REF_ID>') WHEN NOT MATCHED THEN INSERT (REF_ID, REG_NO, STATUS, CR_BY, CR_DTIMES, RUN_INSTANCE_ID, SESSION_ID, ACTIVITY, PROCESS, COMMENTS  <IN_ADD_COL>) values('<REF_ID>', '<REG_NO>', '<STATUS>', '<CR_BY>', '<CR_DTIMES>', '<RUN_INSTANCE_ID>', '<SESSION_ID>', '<ACTIVITY>', '<PROCESS>', '<COMMENTS>'  <IN_ADD_VAL>) WHEN MATCHED THEN UPDATE SET REG_NO = '<REG_NO>', STATUS = '<STATUS>', UPD_BY = '<UPD_BY>', UPD_DTIMES = '<UPD_DTIMES>', SESSION_ID = '<SESSION_ID>', ACTIVITY = '<ACTIVITY>', PROCESS = '<PROCESS>', COMMENTS = '<COMMENTS>' <IN_ADD_COL_VAL>");
        inserPacketTrackerQueryMap.put(DBTypes.MSSQL, "IF EXISTS (SELECT * FROM <TABLE_NAME> WHERE RUN_INSTANCE_ID = '<RUN_INSTANCE_ID>' AND REF_ID = '<REF_ID>') UPDATE <TABLE_NAME> SET REF_ID = '<REF_ID>', REG_NO = '<REG_NO>', STATUS = '<STATUS>', UPD_BY = '<UPD_BY>', UPD_DTIMES = '<UPD_DTIMES>', RUN_INSTANCE_ID = '<RUN_INSTANCE_ID>', SESSION_ID = '<SESSION_ID>',  ACTIVITY = '<ACTIVITY>', PROCESS = '<PROCESS>', COMMENTS = '<COMMENTS>'  <IN_ADD_COL_VAL> WHERE RUN_INSTANCE_ID = '<RUN_INSTANCE_ID>' AND REF_ID = '<REF_ID>' ELSE INSERT INTO <TABLE_NAME> (REF_ID, REG_NO, STATUS, CR_BY, CR_DTIMES, RUN_INSTANCE_ID, SESSION_ID, ACTIVITY, PROCESS, COMMENTS  <IN_ADD_COL>) VALUES('<REF_ID>', '<REG_NO>', '<STATUS>', '<CR_BY>', '<CR_DTIMES>', '<RUN_INSTANCE_ID>', '<SESSION_ID>', '<ACTIVITY>', '<PROCESS>', '<COMMENTS>'  <IN_ADD_VAL>)");

        queryMap = new HashMap<>();
        queryMap.put(RegistrationConstants.OFFSET_TRACKER_TABLE_NAME, inserQuerytMap);
        queryMap.put(RegistrationConstants.TRACKER_TABLE_NAME, inserPacketTrackerQueryMap);
    }

    public static String getInsertQueries(String  tableName, DBTypes dbType) {
        return queryMap.get(tableName).get(dbType);
    }
}
